language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=due

script:
- cd DualVNH5019MotorShield
- for e in $(find examples -name \*.ino); do
    platformio ci --board=$BOARD --lib=. $e;
  done
