language: python
python:
 - "2.7"

sudo: false
cache:
 directories:
  - "~/.platformio"

env:
 - PLATFORMIO_CI_SRC=DualVNH5019MotorShield/examples/Demo/Demo.ino

install:
 - pip install -U platformio

script:
 - platformio ci --lib="DualVNH5019MotorShield" --board=uno --board=leonardo --board=megaatmega2560 --board=due
